CREATE TABLE "SHARDING_TEST"."T_TEST_0"
(
    "ID" BIGINT NOT NULL,
    "NUM" INT,
    "NAME" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_0"."NAME" IS '姓名';
COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_0"."NUM" IS '编号';


CREATE TABLE "SHARDING_TEST"."T_TEST_1"
(
    "ID" BIGINT NOT NULL,
    "NUM" INT,
    "NAME" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_1"."NAME" IS '姓名';
COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_1"."NUM" IS '编号';


CREATE TABLE "SHARDING_TEST"."T_TEST_2"
(
    "ID" BIGINT NOT NULL,
    "NUM" INT,
    "NAME" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_2"."NAME" IS '姓名';
COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_2"."NUM" IS '编号';


CREATE TABLE "SHARDING_TEST"."T_TEST_DATE_2024_01"
(
    "ID" BIGINT NOT NULL,
    "CREATE_DATE" VARCHAR(100),
    "NAME" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_DATE_2024_01"."CREATE_DATE" IS '日期';
COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_DATE_2024_01"."NAME" IS '姓名';


CREATE TABLE "SHARDING_TEST"."T_TEST_DATE_2024_02"
(
    "ID" BIGINT NOT NULL,
    "CREATE_DATE" VARCHAR(100),
    "NAME" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_DATE_2024_02"."CREATE_DATE" IS '日期';
COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_DATE_2024_02"."NAME" IS '姓名';


CREATE TABLE "SHARDING_TEST"."T_TEST_DATE_2024_03"
(
    "ID" BIGINT NOT NULL,
    "CREATE_DATE" VARCHAR(100),
    "NAME" VARCHAR(100),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_DATE_2024_03"."CREATE_DATE" IS '日期';
COMMENT ON COLUMN "SHARDING_TEST"."T_TEST_DATE_2024_03"."NAME" IS '姓名';


